name: Docker Publish (Production Images)

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  get-latest-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build images
        uses: docker/build-push-action@v6
        with:
          push: $REGISTRY/$IMAGE:latest